### ISSUE TITLE
Language can not be changed to English under Linux

### ISSUE THREAD

**Issue by randomdev4578** [Strawberry-Software-Industries/SecureCloud#1]
I tried to set the language of SecureCloud to English, however, I was unsuccessful.

What I tried:
`nano config/language.conf`
I removed `german` and put `english` there, but it just doesn`t work. 

Can someone help me?

OS: Raspberry Pi OS 11 (Bullseye)
Python Version: 3.10
SecureCloud Build: v1.7 Release Candidate 4 ([Release Link](https://github.com/Strawberry-Software-Industries/SecureCloud/releases/tag/v1.7-rc4))

**Comment by Juliandev02** [comment]
Hey @randomdev4578 
This seems to be a bug that was also seen in **Bug #2**. The whole thing is a Linux formatting error, and Python does not read out `english` there, it reads `english\n`.
With the upload path it was `/shared/\n` instead of `/shared/`.

![image](https://user-images.githubusercontent.com/81520713/149676814-7c41b77c-5ff6-48c0-9852-12b346716d84.png) <br>

With Release Candidate 4 I will work on fixing this bug.

**Comment by randomdev4578** [comment]
Thanks.

**Comment by Juliandev02** [comment]
I will fix this bug with release Cadidate 5. Thanks for the issue. If you have any questions, please ask them now, otherwise I will close the issue. You can reopen it anytime.
